sonar.projectKey=chrsthper_FullstackExpense
sonar.organization=pso10a
sonar.sources=.
sonar.exclusions=node_modules/**,public/css/**,public/img/**,public/*.html,__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

